# 触发构建 2023-02-20 19:54:42
alternate: Vision

menu:
  home: / || home
  about: /about/ || user
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  # friends: /friends/ || heart
  # links: /links/ || magic

social:
  github: https://github.com/v-immor || github || "#191717"
  #google: https://plus.google.com/yourname || google
  # twitter: https://twitter.com/yourname || twitter || "#00aff0"
  # zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  # weibo: https://weibo.com/yourname || weibo || "#ea716e"
  # about: https://about.me/yourname || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  #youtube: https://youtube.com/yourname || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

widgets:
  random_posts: true # 显示随机文章
  recent_comments: true # 显示最近评论

# 页尾全站统计
footer:
  since: 2022
  count: true
# 打赏
reward:
  # If true, reward will be displayed in every article by default.
  enable: false

# 文章界面统计
post:
  count: true

loader:
  start: false # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画

sidebar:
  # Sidebar Position.
  position: right
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: avatar.png

markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer:
    quotes: '“”‘’'
  plugins: # markdown-it 插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的 class 名称，shoka 主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: markdown-it-furigana
        enable: true
        options:
          fallbackParens: '()'
    - plugin:
        name: markdown-it-spoiler
        enable: true
        options:
          title: '你知道得太多了'

minify:
  html:
    enable: true
    exclude: # 排除 hexo-feed 用到的模板文件
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

autoprefixer:
  exclude:
    - '*.min.css'

valine:
  appId: TlRgjpt7aWX4tVB9FZ3HokVV-gzGzoHsz
  appKey: eUKodKg5zn2TDUsa95eUbkVG
  placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-CN
  visitor: true # 文章访问量统计
  NoRecordIP: false # 不记录 IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true # 默认打开评论框输入特效
  tagMeta:
    visitor: 新朋友
    master: 主人
    friend: 小伙伴
    investor: 金主粑粑
  tagColor:
    visitor: "#855194"
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com

feed:
  limit: 20
  order_by: '-date'
  tag_dir: false
  category_dir: false
  rss:
    enable: true
    template: 'themes/shoka/layout/_alternate/rss.ejs'
    output: 'rss.xml'
  atom:
    enable: true
    template: 'themes/shoka/layout/_alternate/atom.ejs'
    output: 'atom.xml'
  jsonFeed:
    enable: true
    template: 'themes/shoka/layout/_alternate/json.ejs'
    output: 'feed.json'
