name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "v16.12.0"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: update config
        run: |
          echo "key-> ${{ vars.VALINE_APPID }} ${{ vars.VALINE_APPKEY}} ${{ vars.ALGOLIA_APPID }} ${{ vars.ALGOLIA_APIKEY }}"
          echo "key2 -> ${{ secrets.ALGOLIA_ADIMINKEY }}"
          npm run config valine.appId ${{ vars.VALINE_APPID }}
          npm run config valine.appKey ${{ vars.VALINE_APPKEY}}
          npm run config algolia.appId ${{ vars.ALGOLIA_APPID }}
          npm run config algolia.apiKey ${{ vars.ALGOLIA_APIKEY }}
          npm run config algolia.adminApiKey ${{ secrets.ALGOLIA_ADIMINKEY }}
      # - name: Clean
      #   run: npm run clean
      - name: Build
        run: npm run build --debug
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public